### ISSUE TITLE
Sample Script "write-file" Fails: Force having an opened workspace, or support no workspace when running on desktop.

### ISSUE THREAD

**Issue by tbpassin** [boltex/scripting-samples-leojs#4]
Trying to run the _write-file_ example script using CTRL-B fails.

At line 2: `const uri = vscode.Uri.joinPath(g.workspaceUri, "text.txt");`, an error is raised:
```
exception executing script
    Cannot read properties of undefined (reading 'path')
```

Running just `g.es(g.workspaceUri)`  raises the exception
```
exception executing script
    workspaceUri is not defined
```
Clearly this script cannot run on its own.  Please provide the missing framework or document how to set up for running the script.

**Comment by boltex** [comment]
@tbpassin First of all, thank you very much Thomas. You are one hell of a beta tester! Really appreciate you finding those bugs... (although I get angry when reading about some bug appearing in my code!) 😄 

Thanks for checking g.workspaceUri. This made me realize I have forgotten to fix a 'workspace' issue I had postponed.

g.workspaceUri being undefined means this bug happens because you're running LeoJS in vscode without a workspace opened! 

I check for that and prevent it when running vscode on the web, but I totally for got to address it when running normally on the desktop! 

**I intend to fix this and support it very soon!! **  but in the meantime please retest while working within a workspace. (e.g. start vscode by right-clicking on a folder in windows, and choosing 'open with vscode'.. or, from an already opened vscode, choose 'open folder' from the file menu)

Please also re-test the 'import any' bug you discovered a few days back in the same manner, to see if it was related to the 'no workspace opened' situation.

Many thanks again for the invaluable beta-testing you provide!! 

Félix

**Comment by tbpassin** [comment]
I don't know what "running on the web" means.  I assume that "running on the desktop" means within vscode.  I also don't know what a "workspace" is.  This is all VS Code lingo that I'm not familiar with yet.  I'm probably not the only one.

**Comment by boltex** [comment]
@tbpassin Thanks for persisting in your inquisitive endeavor 😄  (I do tend to act like everyone knows vscode heh!)

>I don't know what "running on the web" means.

'running on the web' is that super-cool feature of vscode & leojs ! Here's the gist of it : https://github.com/boltex/leojs?tab=readme-ov-file#web-based-development It's also the very first feature showcased in that 'features-demo' video-clip https://www.youtube.com/watch?v=M_mKXSbVGdE (Pressing the 'dot' on your keyboard when browsing your repository on github to edit it live 'on the web')

>I also don't know what a "workspace" is. 

a 'workspace' in vscode, said simply, is when you open a folder for editing. Vscode is meant to work on folders, akin to git, not on single file(s). (vscode supports opening on a 'file' basis, but that is equivalent to opening in notepad and many features will be missing) But to try out LeoJS within a workspace, just start vscode by right-clicking on a folder and doing 'open with vscode', or on a terminal, navigate into your project folder, and launch vscode with `code .`  (code and a 'dot') . See this for a proper overview https://code.visualstudio.com/docs/editor/workspaces

Having addressed those definitions, I also now realize that the 'writing an external file' script sample should have been split in two different scripts for two distinct use-cases that may be useful to distinguish: 

1- write a file relative to the current workspace. 
2- write a file with arbitrary path.

So that the samples address the 'building of the effective URI of the file to be written' as the call to vscode.workspace.fs.writeFile() is trivial. 

I'll address this in a few days.

Thanks again Thomas for having brought this to my attention.

**Comment by tbpassin** [comment]
That's very interesting!  To make it work fully I had to set my javascript blocker and UOrigin to allow everything for the site.

One question - once I switch into the VSCode view by pressing ".", how can I switch back?  I mean without opening a new tab in the browser.
